### ISSUE TITLE
Display is corrupted with USE_OPENGL on macOS highdpi systems

### ISSUE THREAD

**Issue by szhorvat** [xaos-project/XaoS#213]
**Describe the bug**

When compiling as `qmake DEFINES+=USE_OPENGL` on macOS, only a quarter of the display area is used on highdpi screens.

**Screenshots**

<img width="792" alt="image" src="https://user-images.githubusercontent.com/1212871/115219007-64a04480-a107-11eb-85b0-37793765bd98.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Qt: 5.15.2 from MacPorts

**Comment by szhorvat** [comment]
(BTW for a program like XaoS it would be really nice if hidpi resolutions could be supported, regardless of this issue. I don't know if that would affect performance: XaoS already adjusts resolution dynamically, so perhaps not. The non-OpenGL version behaves correctly, but in fact it runs in low resolution.)

**Comment by trathborne** [comment]
I have the same problem on Ubuntu 22.04 with Qt6 6.2.4 , though my outside is black (different palette I guess) and the scale is different, a bit bigger than in this screenshot. Oh, and fullscreen mode doesn't hide the menu.

Setting QT_SCALE_FACTOR=0.66666666666 fixes the size.

I have a weird setup to make Qt apps look right. Gtk theme is 200 dpi, because this makes Gtk fonts just right, and:

```
$ printenv | grep QT | sort
QT_ACCESSIBILITY=1
QT_FONT_DPI=144
QT_QPA_PLATFORMTHEME=qt5ct
```

In any case ... it _should_ be possible to make the OpenGL widget just use all the pixels, right?

**Comment by kovzol** [comment]
Sorry guys, I am unsure why it is required to use the OpenGL driver. Is the non-OpenGL way not optimal? (I've just fixed the OpenGL port last week because it did not work properly with Qt 6.)

**Comment by trathborne** [comment]
The non-OpenGL way is just fine. I was just testing the OpenGL driver because I saw it go by in the changelog!

**Comment by szhorvat** [comment]
I just tried this with 4.3.3 and it's still broken (as in the display is quarter size) but it seems noticeably faster than the default driver.
